### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by mwilson221** [jdtuck/fdasrsf_python#43]
I'm trying to install fdasrsf from a jupyter notebook, using

!git clone https://github.com/jdtuck/fdasrsf_python.git
!pip install ./fdasrsf_python

and I get 

note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fdasrsf
ERROR: Could not build wheels for fdasrsf, which is required to install pyproject.toml-based projects

any help would be appreciated

Full output:

Processing c:\users\micha\documents\github\machine-learning\untitled folder\fdasrsf_python
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: Cython in c:\users\micha\anaconda3\lib\site-packages (from fdasrsf==2.5.10) (3.0.10)
Requirement already satisfied: matplotlib in c:\users\micha\anaconda3\lib\site-packages (from fdasrsf==2.5.10) (3.5.1)
Requirement already satisfied: numpy in c:\users\micha\anaconda3\lib\site-packages (from fdasrsf==2.5.10) (1.21.6)
Requirement already satisfied: scipy in c:\users\micha\appdata\roaming\python\python39\site-packages (from fdasrsf==2.5.10) (1.11.1)
Requirement already satisfied: joblib in c:\users\micha\appdata\roaming\python\python39\site-packages (from fdasrsf==2.5.10) (1.3.2)
Requirement already satisfied: patsy in c:\users\micha\anaconda3\lib\site-packages (from fdasrsf==2.5.10) (0.5.2)
Requirement already satisfied: tqdm in c:\users\micha\anaconda3\lib\site-packages (from fdasrsf==2.5.10) (4.65.0)
Requirement already satisfied: six in c:\users\micha\anaconda3\lib\site-packages (from fdasrsf==2.5.10) (1.16.0)
Requirement already satisfied: numba in c:\users\micha\anaconda3\lib\site-packages (from fdasrsf==2.5.10) (0.55.1)
Requirement already satisfied: cffi>=1.0.0 in c:\users\micha\anaconda3\lib\site-packages (from fdasrsf==2.5.10) (1.16.0)
Requirement already satisfied: pyparsing in c:\users\micha\anaconda3\lib\site-packages (from fdasrsf==2.5.10) (3.0.9)
Requirement already satisfied: pycparser in c:\users\micha\anaconda3\lib\site-packages (from cffi>=1.0.0->fdasrsf==2.5.10) (2.21)
Requirement already satisfied: cycler>=0.10 in c:\users\micha\anaconda3\lib\site-packages (from matplotlib->fdasrsf==2.5.10) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\micha\anaconda3\lib\site-packages (from matplotlib->fdasrsf==2.5.10) (4.51.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\micha\anaconda3\lib\site-packages (from matplotlib->fdasrsf==2.5.10) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\micha\anaconda3\lib\site-packages (from matplotlib->fdasrsf==2.5.10) (23.2)
Requirement already satisfied: pillow>=6.2.0 in c:\users\micha\anaconda3\lib\site-packages (from matplotlib->fdasrsf==2.5.10) (10.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\micha\anaconda3\lib\site-packages (from matplotlib->fdasrsf==2.5.10) (2.8.2)
Collecting llvmlite<0.39,>=0.38.0rc1 (from numba->fdasrsf==2.5.10)
  Using cached llvmlite-0.38.1-cp39-cp39-win_amd64.whl.metadata (4.7 kB)
Requirement already satisfied: setuptools in c:\users\micha\anaconda3\lib\site-packages (from numba->fdasrsf==2.5.10) (68.2.2)
Requirement already satisfied: colorama in c:\users\micha\anaconda3\lib\site-packages (from tqdm->fdasrsf==2.5.10) (0.4.6)
Using cached llvmlite-0.38.1-cp39-cp39-win_amd64.whl (23.2 MB)
Building wheels for collected packages: fdasrsf
  Building wheel for fdasrsf (pyproject.toml): started
  Building wheel for fdasrsf (pyproject.toml): finished with status 'error'
Failed to build fdasrsf

  error: subprocess-exited-with-error
  
  Building wheel for fdasrsf (pyproject.toml) did not run successfully.
  exit code: 1
  
  [108 lines of output]
  not modified: 'build\\_DP.c'
  generating build\_DP.c
  (already up-to-date)
  running bdist_wheel
  running build
  running build_py
  copying fdasrsf\bayesian_functions.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\boxplots.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\curve_functions.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\curve_pcr_regression.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\curve_regression.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\curve_stats.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\elastic_changepoint.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\elastic_glm_regression.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\fPCA.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\fPLS.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\geodesic.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\geometry.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\gp.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\image.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\image_functions.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\interparc.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\kmeans.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\pcr_regression.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\plot_style.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\rbfgs.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\regression.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\time_warping.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\tolerance.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\umap_metric.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\utility_functions.py -> build\lib.win-amd64-cpython-39\fdasrsf
  copying fdasrsf\__init__.py -> build\lib.win-amd64-cpython-39\fdasrsf
  running egg_info
  writing fdasrsf.egg-info\PKG-INFO
  writing dependency_links to fdasrsf.egg-info\dependency_links.txt
  writing requirements to fdasrsf.egg-info\requires.txt
  writing top-level names to fdasrsf.egg-info\top_level.txt
  reading manifest file 'fdasrsf.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE.txt'
  writing manifest file 'fdasrsf.egg-info\SOURCES.txt'
  running build_ext
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  C:\Users\micha\AppData\Local\Temp\pip-build-env-sw7hp0i0\overlay\Lib\site-packages\numpy\distutils\system_info.py:1914: UserWarning:
      Optimized (vendor) Blas libraries are not found.
      Falls back to netlib Blas library which has worse performance.
      A better performance should be easily gained by switching
      Blas library.
    if self._calc_info(blas):
  C:\Users\micha\AppData\Local\Temp\pip-build-env-sw7hp0i0\overlay\Lib\site-packages\numpy\distutils\system_info.py:1914: UserWarning:
      Blas (http://www.netlib.org/blas/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [blas]) or by setting
      the BLAS environment variable.
    if self._calc_info(blas):
  C:\Users\micha\AppData\Local\Temp\pip-build-env-sw7hp0i0\overlay\Lib\site-packages\numpy\distutils\system_info.py:1914: UserWarning:
      Blas (http://www.netlib.org/blas/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [blas_src]) or by setting
      the BLAS_SRC environment variable.
    if self._calc_info(blas):
  Traceback (most recent call last):
    File "C:\Users\micha\anaconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\micha\anaconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\micha\anaconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\micha\AppData\Local\Temp\pip-build-env-sw7hp0i0\overlay\Lib\site-packages\setuptools\build_meta.py", line 410, in build_wheel
      return self._build_with_temp_dir(
    File "C:\Users\micha\AppData\Local\Temp\pip-build-env-sw7hp0i0\overlay\Lib\site-packages\setuptools\build_meta.py", line 395, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\micha\AppData\Local\Temp\pip-build-env-sw7hp0i0\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 126, in <module>
    File "C:\Users\micha\AppData\Local\Temp\pip-build-env-sw7hp0i0\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
      return run_commands(dist)
    File "C:\Users\micha\AppData\Local\Temp\pip-build-env-sw7hp0i0\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
      dist.run_commands()
    File "C:\Users\micha\AppData\Local\Temp\pip-build-env-sw7hp0i0\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "C:\Users\micha\AppData\Local\Temp\pip-build-env-sw7hp0i0\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
      super().run_command(command)
    File "C:\Users\micha\AppData\Local\Temp\pip-build-env-sw7hp0i0\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\micha\AppData\Local\Temp\pip-build-env-sw7hp0i0\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
      self.run_command("build")
    File "C:\Users\micha\AppData\Local\Temp\pip-build-env-sw7hp0i0\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
      self.distribution.run_command(command)
    File "C:\Users\micha\AppData\Local\Temp\pip-build-env-sw7hp0i0\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
      super().run_command(command)
    File "C:\Users\micha\AppData\Local\Temp\pip-build-env-sw7hp0i0\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\micha\AppData\Local\Temp\pip-build-env-sw7hp0i0\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
      self.run_command(cmd_name)
    File "C:\Users\micha\AppData\Local\Temp\pip-build-env-sw7hp0i0\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
      self.distribution.run_command(command)
    File "C:\Users\micha\AppData\Local\Temp\pip-build-env-sw7hp0i0\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
      super().run_command(command)
    File "C:\Users\micha\AppData\Local\Temp\pip-build-env-sw7hp0i0\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\micha\AppData\Local\Temp\pip-build-env-sw7hp0i0\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run
      self.build_extensions()
    File "C:\Users\micha\AppData\Local\Temp\pip-build-env-sw7hp0i0\overlay\Lib\site-packages\findblas\distutils.py", line 33, in build_extensions
      raise ValueError(txt)
  ValueError: Found BLAS library at:
  C:/Users/micha/anaconda3/Library/bin\mkl_rt.1.dll
  But .lib files are missing! Please reinstall it (e.g. 'pip install mkl-devel').
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fdasrsf
ERROR: Could not build wheels for fdasrsf, which is required to install pyproject.toml-based projects

**Comment by mwilson221** [comment]
Sorry nevermind I figured it out
